export { default as About } from './About';
export { default as Dashboard } from './Dashboard';
export { default as Error } from './Error';
export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Products } from './Products';
export { default as ProtectedRoute } from './ProtectedRoute';
export { default as SharedLayout } from './SharedLayout';
export { default as SingleProduct } from './SingleProduct';
